language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm run test -- --coverage

after_success:
    - docker build -t mcadams0001/multi-client ./client
    - docker build -t mcadams0001/multi-nginx ./nginx
    - docker build -t mcadams0001/multi-server ./server
    - docker build -t mcadams0001/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "${DOCKER_ID}" --password-stdin
    - docker push mcadams0001/multi-client
    - docker push mcadams0001/multi-nginx
    - docker push mcadams0001/multi-server
    - docker push mcadams0001/multi-worker